### ISSUE TITLE
Doc update needed

### ISSUE THREAD

**Issue by steve-hickman-epistimis** [TypeFox/xtext2langium#10]
[Blog post](https://www.typefox.io/blog/xtext-to-langium/) refers to v 0.3.0 - which is not current.

Neither the blog post nor the README.md file refer to `<location>` needed for the `target.target` file. Both should be updated to have full instructions.

**Comment by dhuebner** [comment]
> Blog post refers to v 0.3.0 - which is not current.

Yes, it was written describing the v0.3.0 version. There is also a link where to find the latest version. 

> Neither the blog post nor the README.md file refer to <location> needed for the target.target file. 

The description about how to work with `.target` file is missing? Or what do you mean?

**Comment by steve-hickman-epistimis** [comment]
Maybe this is my experience only, but I was unable to get this to work using Maven until I added the following to the `target.target` file in the `<dsl>.target` project:
```
<location includeAllPlatforms="false" includeConfigurePhase="false" includeMode="planner" includeSource="true" type="InstallableUnit">
   <unit id="io.typefox.xtext2langium" version="0.0.0"/>
   <repository location="https://typefox.github.io/xtext2langium/download/updates/v0.4.0/"/>
</location>

```

**Comment by dhuebner** [comment]
@steve-hickman-epistimis 
I see, thanks! You are right, we should add a hint for Tycho users.

**Comment by dhuebner** [comment]
Updated.
