### ISSUE TITLE
Generating dependent grammars doesn't name the dependency

### ISSUE THREAD

**Issue by steve-hickman-epistimis** [TypeFox/xtext2langium#2]
I have several XText grammars with dependencies as follows:
```
grammar com.epistimis.privacy.Privacy with com.epistimis.face.Face
grammar com.epistimis.face.Face with com.epistimis.uddl.Uddl
grammar com.epistimis.uddl.Uddl with org.eclipse.xtext.common.Terminals
```
When I generate from the Privacy grammar, I get the following files:
```
Privacy.langium
Face.langium
Face-types.langium
Uddl.langium
Uddl-types.langium
Terminals.langium
```

`Uddl.langium` is generated without the following:
```
grammar Uddl
```

Similarly, `Face.langium` is generated without
```
grammar Face
```

These generated grammars should be named because it is possible that some users will edit just Uddl files or just Face files.

**Comment by dhuebner** [comment]
@steve-hickman-epistimis 
Thanks for reporting. I will look into it

**Comment by dhuebner** [comment]
Resolved in master
