### ISSUE TITLE
Add imports for transitive imported grammars

### ISSUE THREAD

**Issue by dhuebner** [TypeFox/xtext2langium#8]
Currently if Grammar A imports B and B imports C. Rules from C can not be used in grammar A.
We need to add an explicit import in those cases.

**Comment by steve-hickman-epistimis** [comment]
I think this has been resolved now in Langium 2.x.  At least, it appears that way as of today.

**Comment by dhuebner** [comment]
@steve-hickman-epistimis 
Thanks for the reminder!
